### ISSUE TITLE
How to add my local plugin in my Docker-compose.yml

### ISSUE THREAD

**Issue by ShubhamPalriwala** [Kong/kong-pongo#242]
I have a custom plugin here created using Pongo at [KongToTheRescue](https://github.com/ShubhamPalriwala/KongToTheRescue/tree/master). I want to create a docker-compose file that users can use to directly test this custom plugin.

I have been able to set up a docker-compose to start a Kong with Postgres containers. However, i am unable to add my custom plugins. How can I do that? Any help would be great
My current Docker-compose consists of:
```yml
version: "3"

networks:
  kong-net:
    driver: bridge

services:
  # Postgres: The database used by Kong
  kong-database:
    image: postgres:9.6
    restart: on-failure
    networks:
      - kong-net
    environment:
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Kong DB migration
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_DATABASE: postgres
      KONG_PG_PASSWORD: kong
    links:
      - kong-database
    depends_on:
      - kong-database

  # Kong CLI
  kong:
    image: kong:latest
    restart: on-failure
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://kong:8001" ]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"
```
